const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2019 - Lulus sd",
      // title: "Academic Degree",
      desc: "SDN 016",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2019/2020 - SMP",
      // title: "Bachelor's Degree",
      desc: "MTs normal islam",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2022/2023 - SMK",
      // title: "Honours Degree",
      desc: "SMKTI airlangga",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-graduation",
      // year: "2019 - present",
      title: "UI/UX Design",
      // desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-graduation",
      // year: "2013 - 2017",
      title: "Web Developer",
      // desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-graduation",
      // year: "2009 - 2013",
      title: "Photography",
      // desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
  ];
export default Data